### ISSUE TITLE
Missing DeepGTAV.asi 

### ISSUE THREAD

**Issue by Hokyjack** [bradenhurl/DeepGTAV-PreSIL#1]
Hello,
I am wondering if in this repo the file "DeepGTAV.asi" shouldn't be presented inside Release folder.
Because I am not seeing this mode being loaded by asiloader and I cannot connect via TCP while the game is running.

Thanks!

**Comment by Hokyjack** [comment]
Problem solved, I just compiled it from source myself

**Comment by Shawnxm** [comment]
How did you compile the source?

**Comment by Ben93kie** [comment]
Sorry,
just out of curiosity, did you encounter the problem that your created .asi-file did not load initially?
