### ISSUE TITLE
What is the use of Secondary Perspectives?

### ISSUE THREAD

**Issue by sharma-n** [bradenhurl/DeepGTAV-PreSIL#16]
Hi!
Thanks for sharing your work. It's super interesting! I have been tinkering with it over the past month to better understand it. I'm wondering why you record secondary perspectives from different vehicles on the road? I can only think of 2 things:

1. To somehow improve the bi-linear interpolation from the depth maps from different perspectives? Do you use these secondary perspectives to improve the final point cloud collected?

2. To collect more data in a single scene, so that we have more samples without moving the cars around or continuing the game. If this is the case, do you see any big problems with this approach?

Thanks for clearing this up in advance!

**Comment by bradenhurl** [comment]
Always glad to hear people are using it! The secondary perspectives were actually created for a secondary paper on cooperative (multi-vehicle) perception. If you're interested here is the [paper](https://arxiv.org/pdf/1909.07867.pdf) and [code](https://github.com/bradenhurl/TruPercept).
