### ISSUE TITLE
How to I get GTA 1.0.1180.2

### ISSUE THREAD

**Issue by soulslicer** [bradenhurl/DeepGTAV-PreSIL#3]
I just bought GTA5 for this, but I can't figure out how to downgrade to this version

**Comment by Hokyjack** [comment]
Here you go:
https://howfix.net/file/patch/download-patch-1-0-1180-2-smugglers-run-gta-5-online/ 

You need to have a Social Club version of the game. After applying patch, make sure you have GTAVLauncherBypass.asi and ScriptHookV installed so the game does not update itself and run it with GTA5.exe file

**Comment by Shawnxm** [comment]
May I ask what is a Social Club version?
Thanks in advance.

**Comment by lvbu2025** [comment]
Isn't that for GTA V online, which technically is a different game than GTA V?
